name: test and Deploy 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest testing.py
      
  build-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t fp-sim6-ec2read .
      - name: set-up
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION
          aws configure set region $AWS_DEFAULT_REGION
          cat ~/.aws/credentials
      - name: Install essentials
        run: |
          aws --version

          # install LightsailCTL Plugin (https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-install-software)
          sudo apt-get update && sudo apt-get -y install curl jq
          curl https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl -o /usr/local/bin/lightsailctl
          chmod +x /usr/local/bin/lightsailctl
      - name: push-container
        run: |
          echo "pushing container"
          # upload the docker image for this pipeline
          aws lightsail push-container-image \
            --service-name memester  \
            --label fp-sim6-ec2read  \
            --image fp-sim6-ec2read

          # get uploaded image (its different every time)
          IMAGE_TAG=$(aws lightsail get-container-images --service memester | jq -r .containerImages[0].image)
          
      - name: deploy
        run: |
          # create a deployment with uploaded docker image
          aws lightsail create-container-service-deployment \
            --service-name memester \
            --containers "{
              \"flask\": {
                \"image\": \"$IMAGE_TAG\",
                \"ports\": {
                  \"5000\": \"HTTP\"
                }
              }
            }" \
            --public-endpoint "{
                  \"containerName\": \"flask\",
                  \"containerPort\": 5000
            }"
